export const REMEDY_CATALOG = [
  {
    id: "tulsi-ginger-brew",
    name: "Tulsi Ginger Brew",
    description: "A warm home brew for mild cough, congestion, and early sore throat support.",
    ingredients: ["Tulsi leaves", "Fresh ginger", "Warm water", "Black pepper", "Honey"],
    steps: [
      "Lightly crush tulsi leaves and sliced ginger.",
      "Simmer them in water for 8 to 10 minutes.",
      "Add a pinch of black pepper and strain.",
      "Use honey only if it is safe for the profile and sip warm.",
    ],
    symptomTags: ["cough", "cold", "sore throat", "congestion"],
    tags: ["Respiratory", "Warm", "Immune support"],
    substitutes: ["Skip honey for sugar-sensitive profiles", "Reduce black pepper for children"],
    colorFrom: "#1e8c84",
    colorTo: "#0f645d",
  },
  {
    id: "warm-salt-gargle",
    name: "Warm Salt Gargle",
    description: "A simple gargle for throat irritation when the member can safely gargle.",
    ingredients: ["Warm water", "Salt"],
    steps: [
      "Mix a small pinch of salt into warm water.",
      "Gargle for 15 to 20 seconds and spit out.",
      "Repeat up to 3 times per day if there is no blood pressure-related salt restriction.",
    ],
    symptomTags: ["sore throat", "cough"],
    tags: ["Throat care", "Simple"],
    substitutes: ["Use plain warm water if salt should be restricted"],
    colorFrom: "#277da1",
    colorTo: "#1d5c78",
  },
  {
    id: "cumin-coriander-fennel",
    name: "Cumin Coriander Fennel Infusion",
    description: "A digestive infusion for bloating, heaviness, and mild acidity after meals.",
    ingredients: ["Cumin seeds", "Coriander seeds", "Fennel seeds", "Warm water"],
    steps: [
      "Lightly crush the seeds.",
      "Simmer them in water for 8 minutes.",
      "Strain and sip warm after meals.",
    ],
    symptomTags: ["bloating", "indigestion", "acidity", "nausea"],
    tags: ["Digestive", "Cooling"],
    substitutes: ["Use mostly coriander if there is heat or acidity"],
    colorFrom: "#d18a1c",
    colorTo: "#a06100",
  },
  {
    id: "ajwain-water",
    name: "Ajwain Relief Water",
    description: "A focused home remedy for gas and sluggish digestion in non-pregnancy profiles.",
    ingredients: ["Ajwain seeds", "Warm water", "Rock salt"],
    steps: [
      "Dry roast ajwain lightly.",
      "Simmer in water for 5 minutes and strain.",
      "Use only a tiny pinch of rock salt when it is safe for blood pressure.",
    ],
    symptomTags: ["bloating", "indigestion", "nausea"],
    tags: ["Digestive", "Warming"],
    substitutes: ["Switch to cumin coriander fennel for gentler support"],
    colorFrom: "#cd6e1a",
    colorTo: "#9a4f07",
  },
  {
    id: "golden-milk",
    name: "Turmeric Night Milk",
    description: "A comforting evening drink for mild body ache, fatigue, and sleep support.",
    ingredients: ["Milk", "Turmeric", "Fresh ginger", "Black pepper"],
    steps: [
      "Warm the milk gently without overboiling.",
      "Whisk in turmeric and a little grated ginger.",
      "Add just a tiny pinch of black pepper and drink warm.",
    ],
    symptomTags: ["joint pain", "fatigue", "sleep trouble", "stress"],
    tags: ["Recovery", "Evening care"],
    substitutes: ["Use lactose-free milk if dairy triggers discomfort"],
    colorFrom: "#c8921c",
    colorTo: "#915d00",
  },
  {
    id: "coriander-cooling-water",
    name: "Coriander Cooling Water",
    description: "A gentle hydration drink for heat, mild acidity, and household hydration support.",
    ingredients: ["Coriander seeds", "Water", "Fresh mint"],
    steps: [
      "Soak coriander seeds in water for a few hours.",
      "Strain, add a little mint, and sip through the day.",
    ],
    symptomTags: ["acidity", "fatigue", "nausea"],
    tags: ["Cooling", "Hydration"],
    substitutes: ["Use plain water if herbs are not tolerated"],
    colorFrom: "#3b9fb6",
    colorTo: "#236d7e",
  },
];
